name: Build and Push Image to ECR

on:
  workflow_dispatch:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Public ECR
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build & tag Docker Image
        run: |
          docker build -t ecs-assignment:latest .
          docker tag ecs-assignment:latest ${{ secrets.ECR_REGISTRY }}/ecs-assignment:latest

      - name: Push Docker Image to ECR
        run: docker push ${{ secrets.ECR_REGISTRY }}/ecs-assignment:latest


